name: on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**/*.tf'
      - 'environments/**/*.tf'

jobs:
  changed_files:
    name: Detect changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - id: changed_files
        name: Get Changed files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c #v46.0.5
        with:
          matrix: true
          dir_names: "true"
          files_yaml: |
            modules:
              - modules/**/*.tf
            environments:
              - environments/**/*.tf

      - name: List all changed files
        # if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          echo ${{ steps.changed_files.outputs }}
    outputs:
      all_changed_files: ${{ steps.changed_files.outputs.all_changed_files }}
      module_changed_dir: ${{ steps.changed_files.outputs.modules_all_changed_files }}
      environments_changed_dir: ${{ steps.changed_files.outputs.environments_all_changed_files }}

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: changed_files
    permissions:
      pull-requests: write
    strategy:
      matrix:
        changed_dir: ${{ fromJson(needs.changed_files.outputs.environments_changed_dir) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Setup env
        run: |
          tf_dir_path="${{ github.workspace }}/${{ matrix.changed_dir }}"
          log_file_path="/tmp/$(basename $tf_dir_path).txt"

          echo "TF_DIR_PATH=$tf_dir_path" >> $GITHUB_ENV
          echo "LOG_FILE_PATH=$log_file_path" >> $GITHUB_ENV

      - name: Trivy Scan
        id: scan
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5
        continue-on-error: true
        with:
          scan-type: config
          hide-progress: true
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: 1
          format: table
          scan-ref: ${{ matrix.changed_dir }}
          # tf-vars: terraform.tfvars
          output: trivy.txt

      - name: set comment output
        run: |
          echo "Location: ${{ env.TF_DIR_PATH }}" >> ${{ env.LOG_FILE_PATH }}
          echo "\`\`\`hcl" >> ${{ env.LOG_FILE_PATH }}
          cat trivy.txt >> ${{ env.LOG_FILE_PATH }}
          echo "\`\`\`" >> ${{ env.LOG_FILE_PATH }}

      - name: Find PR comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "Location: ${{ env.TF_DIR_PATH }}"

      - name: Create PR comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.number }}
          body-path: ${{ env.LOG_FILE_PATH }}
          reactions: rocket

      - name: Update PR comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-path: ${{ env.LOG_FILE_PATH }}
          edit-mode: replace
          reactions: hooray

      # - name: Report to PR
      #   uses: actions/github-script@v7
      #   if: github.event_name == 'pull_request'
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const fs = require('fs');
      #       const report = fs.readFileSync('trivy.txt', 'utf8');
      #       const output = `Trivy report:
      #       \`\`\`hcl\n
      #       ${report.length > 0 ? report : 'No issues found'}
      #       \`\`\`

      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: output
      #       })
      # - name: Trivy Scan
      #   id: scan
      #   uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5
      #   with:
      #     scan-type: config
      #     hide-progress: true
      #     ignore-unfixed: true
      #     # severity: 'CRITICAL,HIGH'
      #     exit-code: 1
      #     format: template
      #     template: '@trivy-pr-template.tpl'
      #     scan-ref: ${{ matrix.changed_dir }}
      #     # tf-vars: terraform.tfvars
      #     output: trivy.json

      # - name: Report vulnerabilities in PR
      #   if: failure() && steps.scan.outcome == 'failure'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   shell: bash
      #   run: |
      #     echo -n "{\"body\":\"### Trivy fs scan - Vulnerabilities detected\nThe following vulnerabilities of HIGH or CRITICAL severity has been detected in the code. Please resolve these before merging the pull request.\n\n" > result.json
      #     cat trivy.json | sort | uniq | tr -d '\n' >> result.json
      #     echo "\"}" >> result.json
      #     curl -X POST -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       -H "Authorization: Bearer $GITHUB_TOKEN" \
      #       ${{ github.event.pull_request.comments_url }} \
      #       -d @result.json

      # - name: Report no vulnerabilities in PR
      #   if: success() && steps.scan.outcome == 'success'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   shell: bash
      #   run: |
      #     echo -n "{\"body\":\"### Trivy fs scan - No vulnerabilities detected\nNo vulnerabilities of HIGH or CRITICAL severity has been detected in the code.\"}" > result.json
      #     curl -X POST -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       -H "Authorization: Bearer $GITHUB_TOKEN" \
      #       ${{ github.event.pull_request.comments_url }} \
      #       -d @result.json

  terraform:
    name: Terraform Environment
    runs-on: ubuntu-latest
    needs: [changed_files ,tests]
    permissions:
      pull-requests: write
    strategy:
      matrix:
        changed_files: ${{ fromJson(needs.changed_files.outputs.environments_changed_dir) }}
    steps:
      - name: Echo matrix
        run: echo ${{ matrix.changed_files }}

      - uses: actions/checkout@v4 # v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup env
        run: |
          tf_dir_path="${{ github.workspace }}/${{ matrix.changed_files }}"
          log_file_path="/tmp/$(basename $tf_dir_path).txt"

          echo "TF_DIR_PATH=$tf_dir_path" >> $GITHUB_ENV
          echo "LOG_FILE_PATH=$log_file_path" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11"

      - name: Terraform Init
        working-directory: ${{ matrix.changed_files }}
        run: |
          terraform init -no-color -input=false

      - name: Terraform Plan
        working-directory: ${{ matrix.changed_files }}
        run: |
          terraform plan -no-color -input=false > tfplan.txt

      - name: Setup TF Plan
        working-directory: ${{ matrix.changed_files }}
        run: |
          echo "## Change detected in the following directories: \`${{ matrix.changed_files }}\` 🚀" >>  ${{ env.LOG_FILE_PATH }}
          # echo "#### Terraform Initialization ⚙️ ${{ steps.init.outcome }}" >>  ${{ env.LOG_FILE_PATH }}
          echo "#### Terraform Plan 📖 ${{ steps.plan.outcome }}" >>  ${{ env.LOG_FILE_PATH }}
          echo "\`\`\`hcl" >>  ${{ env.LOG_FILE_PATH }}
          echo "$(cat tfplan.txt)" >>  ${{ env.LOG_FILE_PATH }}
          echo "\`\`\`" >>  ${{ env.LOG_FILE_PATH }}
          echo "*Pushed by: @${{ github.actor }}, Action: ${{ github.event_name }}*" >>  ${{ env.LOG_FILE_PATH }}

      - name: Find PR comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
        id: pr
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "## Change detected in the following directories: ${{ matrix.changed_files }} 🚀"

      - name: Create PR comment
        if: steps.pr.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.number }}
          body-path: ${{ env.LOG_FILE_PATH }}
          reactions: rocket

      - name: Update PR comment
        if: steps.pr.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          comment-id: ${{ steps.pr.outputs.comment-id }}
          body-path: ${{ env.LOG_FILE_PATH }}
          edit-mode: replace
          reactions: hooray